version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "8102:8102"
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      mysql-db:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worker.celery worker --loglevel=INFO
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis
      - app
  
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ersp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql-db", "-P", "3306", "-u", "root", "-proot"]
      interval: 5s
      timeout: 2s
      retries: 5
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

